sonar.projectKey=mohamedamine050_project_data_engineering

# Code analysé
sonar.sources=src
sonar.tests=tests

# Exclusions (important)
sonar.exclusions=infra/**,bootstrap/**,.github/**,**/*.tf

# Coverage
sonar.python.coverage.reportPaths=coverage.xml
